### PR TITLE
Added Wordpress, MongoDB, Laravel, Symfony, PhoneGap icons & SVG icons

### PR DESCRIPTION
**Pull request by suranyami**
This fixes issues #3, #4, #5, #6, also adds SVG.

Also, I think the with-build-scripts branch should really be merged into master now.

I had an enquiry from someone adding to the Atom editor package file-icons who was confused because the version of font-mfizz in master is the old version.

If you like, you could add me as a collaborator on this project, and I could handle these actions for you?

Also added Javascript-alt icon that renders better when small.

Thanks in advance.

### CODE REVIEW

**Comment by suranyami** [comment]
Finally! I should probably let the author of the `file-icons` package for the Atom editor know… they've been using my fork for the last 18 months, because these PRs were being ignored.

**Comment by jjlauer** [comment]
Yeah, sorry about how darn long this took.  100% hobby and 2 kids later :-)

Appreciate the work you did and my goal w/ v2.0 is to simply let the
community contribute.  Builds should be easy for me to do periodically and
publish.

**Comment by suranyami** [comment]
No problem: can totally empathise.

As I mentioned in the PR description, if you add me as a contributor to this repo I'd be happy to help out.

Have you tried the build scripts I added? They certainly helped me a lot. Made the build process fairly foolproof.

**Comment by jjlauer** [comment]
Added you as a collaborator.

Yes, I took your tweaked build scripts and tweaked them a bit more.

Your 'sed' changes didn't work on linux and I fixed them again for
FontCustom v1.3.8.   Haven't tried them on OSX yet.

**Comment by suranyami** [comment]
Excellent!

**Pull request merged**
