### PR TITLE
Added New Icons

### PR DESCRIPTION
**Pull request by wakqasahmed**
Kindly merge.

Thank You

### CODE REVIEW

**Comment by jjlauer** [comment]
Hey, these are great.  I noticed just a few them need their screen size adjusted to chop off extra space around them.  For example, codeigniter.

I have some tips on how to do this here:
https://github.com/fizzed/font-mfizz/blob/master/DEVELOPMENT.md#preparing-the-artwork

Let me know if you can't figure it out and I'll see about trying to work on them next week.  But if you can fix them, I'll have no problem then merging this PR.

**Comment by k-funk** [comment]
:metal:

**Comment by queso** [comment]
Would love the react icon in the set, any updates on this?

**Comment by imcodingideas** [comment]
What needs to happen to get these pulled in?

**Comment by suranyami** [comment]
@imcodingideas: See comment above by @jjauer

**Pull request merged**
